import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  scrollViewContainer: {
    flex: 1,
    backgroundColor: '#2c3e50',
  },
  contentContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2c3e50',
    paddingHorizontal: 30,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#333',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
    flex: 1,
    marginRight: 15,
    lineHeight: 34,
    textAlign: 'left',
  },
  favoriteButton: {
    padding: 10,
    borderRadius: 25,
    backgroundColor: '#2d2d2d',
    borderWidth: 1,
    borderColor: '#444',
  },
  imagem: {
    width: '100%',
    height: 220,
    borderRadius: 12,
    marginVertical: 15,
    backgroundColor: '#333',
  },
  detailText: {
    fontSize: 14,
    color: '#b0b0b0',
    marginBottom: 15,
    fontStyle: 'italic',
    textAlign: 'center',
    backgroundColor: '#333',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  descriptionText: {
    fontSize: 16,
    color: '#e0e0e0',
    lineHeight: 24,
    marginBottom: 20,
    textAlign: 'justify',
    backgroundColor: '#2d2d2d',
    padding: 18,
    borderRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#27ae60',
  },
  extraDetails: {
    fontSize: 15,
    color: '#e0e0e0',
    lineHeight: 22,
    marginBottom: 25,
    padding: 18,
    backgroundColor: '#2d2d2d',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#333',
    textAlign: 'justify',
  },
  errorText: {
    fontSize: 18,
    color: '#ff6b6b',
    textAlign: 'center',
    marginBottom: 25,
    fontWeight: '600',
    lineHeight: 24,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#b0b0b0',
    fontWeight: '500',
  },
  buttonContainer: {
    marginTop: 20,
    borderRadius: 8,
    overflow: 'hidden',
  },
  infoSection: {
    backgroundColor: '#2d2d2d',
    marginBottom: 15,
    borderRadius: 10,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: '#27ae60',
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#27ae60',
    marginBottom: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 25,
    gap: 10,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: '#636e72',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
});